# Generated by Django 3.0.3 on 2020-02-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_campsite_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='campsite',
            name='img_url',
            field=models.TextField(default='https://primereviews.org/wp-content/uploads/2019/09/Camping-Tent-with-RV-in-the-Background.jpg'),
            preserve_default=False,
        ),
    ]
