# Generated by Django 3.0.2 on 2020-02-07 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0003_campsite_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='user',
        ),
        migrations.AddField(
            model_name='campsite',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('campsite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Campsite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
