# Generated by Django 3.0.2 on 2020-02-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200207_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campsite',
            name='location',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='campsite',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
