# Generated by Django 3.0.2 on 2020-02-10 22:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0007_auto_20200210_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='user',
        ),
        migrations.AddField(
            model_name='campsite',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
