# Generated by Django 3.0.2 on 2020-02-10 23:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0008_auto_20200210_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campsite',
            name='users',
        ),
        migrations.AddField(
            model_name='campsite',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
