# Generated by Django 3.0.2 on 2020-02-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20200211_0739'),
        ('main_app', '0009_auto_20200210_2312'),
    ]

    operations = [
    ]
